version: '3.5'

services:   

  postgres:
    image: postgres:12.4-alpine
    container_name: postgres-leggo-twitter
    restart: unless-stopped
    env_file:
      - ${TWITTER_API_DADOS_PATH:-.}/.env
    volumes:
      - leggo_twitter_data:/var/lib/postgresql/data/
    ports:
      - 7688:5432
    networks:
      - twitternet
  
  feed:
    build:
      context: ${TWITTER_API_DADOS_PATH:-.}/feed
    container_name: feed-leggo-twitter
    image: feed-leggo-twitter-image
    env_file:
      - ${TWITTER_API_DADOS_PATH:-.}/.env
    volumes:
      - ${TWITTER_API_DADOS_PATH:-.}/feed:/code
      - ${TWITTER_API_DADOS_PATH:-.}/data:/data
    ports:
      - 7689:7689
    depends_on:
      - postgres
    networks:
      - twitternet
  
  r-twitter-service:
    build:
      context: ${TWITTER_API_DADOS_PATH:-.}
    container_name: r-leggo-twitter
    image: r-leggo-twitter-image
    environment:
      - PASSWORD=${PASSWORD:-secret}
    volumes:
      - ${TWITTER_API_DADOS_PATH:-.}/code:/leggo-twitter-dados/code
      - ${TWITTER_API_DADOS_PATH:-.}/data:/leggo-twitter-dados/data
    networks:
      - twitternet

networks:
  twitternet:
    name: leggo_twitter_network
      
volumes:
  leggo_twitter_data: