version: '3.5'

services:   

  postgres:
    image: postgres:12.4-alpine
    container_name: postgres-leggo-twitter
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-leggotwitter}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-secret}
      - TZ=GMT
    volumes:
      - leggo_twitter_data:/var/lib/postgresql/data/
    ports:
      - 7688:5432
    networks:
      - twitternet
  
  feed:
    build:
      context: feed/
    container_name: feed-leggo-twitter
    image: feed-leggo-twitter-image
    env_file:
      - .env
    volumes:
      - ./feed:/code
    ports:
      - 7689:7689
    depends_on:
      - postgres
    networks:
      - twitternet

networks:
  twitternet:
    external:
      name: leggo_twitter_network
      
volumes:
  leggo_twitter_data: