version: '3.5'

services:   

  postgres:
    env_file:
      - ${TWITTER_API_DADOS_PATH:-.}/.env
  
  feed:
    env_file:
      - ${TWITTER_API_DADOS_PATH:-.}/.env
    volumes:
      - ${TWITTER_API_DADOS_PATH:-.}/feed:/code
      - ${TWITTER_API_DADOS_PATH:-.}/data:/data
  
  r-twitter-service:
    environment:
      - PASSWORD=${PASSWORD:-secret}
    volumes:
      - ${TWITTER_API_DADOS_PATH:-.}/code:/leggo-twitter-dados/code
      - ${TWITTER_API_DADOS_PATH:-.}/data:/leggo-twitter-dados/data
  
  crawler-twitter-service:
    env_file:
      - ${TWITTER_API_DADOS_PATH:-.}/.env
    volumes:
      - ${TWITTER_API_DADOS_PATH:-.}/crawler:/crawler
      - ${TWITTER_API_DADOS_PATH:-.}/data:/data
