version: '3.5'

services:   

  postgres:
    image: postgres:12.4-alpine
    shm_size: 4g
    container_name: postgres-leggo-twitter
    restart: unless-stopped
    volumes:
      - leggo_twitter_data:/var/lib/postgresql/data/
    ports:
      - 7688:5432
    networks:
      - twitternet
  
  feed:
    build:
      context: ${TWITTER_API_DADOS_PATH:-.}/feed
    container_name: feed-leggo-twitter
    image: feed-leggo-twitter-image
    depends_on:
      - postgres
    networks:
      - twitternet
  
  r-twitter-service:
    build:
      context: ${TWITTER_API_DADOS_PATH:-.}
    container_name: r-leggo-twitter
    image: r-leggo-twitter-image
    networks:
      - twitternet

  crawler-twitter-service:
    build:
      context: ${TWITTER_API_DADOS_PATH:-.}/crawler
    container_name: crawler-leggo-twitter
    image: crawler-leggo-twitter-image
    networks:
      - twitternet

networks:
  twitternet:
    name: leggo_twitter_network
      
volumes:
  leggo_twitter_data: