.URL_MENCOES_CR <- "https://docs.google.com/spreadsheets/d/e/2PACX-1vQkC_mEvLxbGxIfwpn8BGn2D15DPWleMeL-dRINuVofUqRdrQziPM7xh3CP-VAVfKYjwMdHs4Yxhazx/pub?gid=1318407739&single=true&output=csv"

POSTGRES_TWEETS_HOST <- Sys.getenv("POSTGRES_TWEETS_HOST")
POSTGRES_TWEETS_DATABASE <- Sys.getenv("POSTGRES_TWEETS_DATABASE")
POSTGRES_TWEETS_USER <- Sys.getenv("POSTGRES_TWEETS_USER")
POSTGRES_TWEETS_PASS <- Sys.getenv("POSTGRES_TWEETS_PASS")
POSTGRES_TWEETS_PORT <- Sys.getenv("POSTGRES_TWEETS_PORT")
